CREATE TABLE ASSOCIATED_ENTITY (
    FILING_NUM TEXT,
    LAYOUT_CODE TEXT,
    ASSOCIATED_ENTITY_ID NUMERIC,
    ASSOCIATED_ENTITY_NAME TEXT,
    ENTITY_FILING_NUMBER NUMERIC,
    ENTITY_FILING_DATE DATE,
    JURISDICTION_COUNTRY TEXT,
    JURISDICTION_STATE TEXT,
    INACTIVE_DATE DATE,
    CAPACITY_ID NUMERIC
);
CREATE INDEX ON ASSOCIATED_ENTITY(FILING_NUM);
CREATE INDEX idx_associated_entity_name ON ASSOCIATED_ENTITY USING gin(to_tsvector('english',ASSOCIATED_ENTITY_NAME));